--- 
- name: Install and configure apache-server 
  hosts: all
  tasks:
    - name: Latest version of httpd and firewalld installed
      ansible.builtin.dnf:
        name:
          - httpd
          - firewalld
        state: latest

    - name: Test html page is installed
      ansible.builtin.copy:
        content: "<h1> TAM YOUR TECH </h1>"
        dest: /var/www/html/index.html

    - name: Firewall enabled and running
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Firewall permits access to httpd service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Web server enabled and running
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

        
- name: register on zabbix
  hosts: all
  roles:
    - role: zabbix_agent
      vars:
        zabbix_local_hostname: "{{ inventory_hostname }}"
        zabbix_local_ip: "{{ private_ip_address }}"
        zabbix_server: "zabbix.sandbox1696.opentlc.com"
        zabbix_server_http_port: "80"
        zabbix_server_protocol: "http"
        zabbix_server_context: "/zabbix"
        zabbix_register_host: true
        zabbix_templates:
          - templateid: 10001
          - templateid: 10265
        zabbix_groups:
          - groupid: 20
