- name: Health check do  trigger Zabbix
  hosts: all
  become: true

  tasks:    
    - name: Reiniciar httpd se estiver parado
      ansible.builtin.systemd:
        name: httpd
        state: restarted
        
    - name: Informar que o serviço foi reiniciado
      ansible.builtin.debug:
        msg: "HTTPD estava parado e foi reiniciado no host {{ zabbix_host }}"
        
