--- 
- name: register on zabbix
  hosts: all
  roles:
    - role: zabbix_agent
      vars:
        zabbix_local_hostname: "{{ inventory_hostname }}"
        zabbix_local_ip: "{{ public_ip_address }}"
        zabbix_server: "http://ec2-52-67-255-50.sa-east-1.compute.amazonaws.com"
        zabbix_server_http_port: "80"
        zabbix_server_protocol: "http"
        zabbix_server_context: "/zabbix"
        zabbix_username: "ansible"
        zabbix_register_host: true
        zabbix_password: "Redhat123"
        zabbix_templates:
          - templateid: 10001
        zabbix_groups:
          - groupid: 2     
          
