---
- name: Zabbix HTTP Fail Monitor
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5000
        path: /httpfail

  rules:
    - name: Executar Health Check via AAP se HTTP falhar
      condition: event.payload.event is defined and event.payload.event == "httpfail"
      actions:
        - debug:
            msg: >
              DEBUG EDA: host={{ event.payload.host | default('') }},
              event={{ event.payload.event | default('') }}
        - run_job_template:
            name: "HealthCheck"
            organization: "Default"
            job_args:
              extra_vars:
                zabbix_host: "{{ event.payload.host | default('') }}"
